name: sajili_mobile
description: A university students' attendance mobile application for lecturers and students
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  camera: ^0.10.3
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  google_mlkit_face_detection: ^0.5.0
  http: ^0.13.5
  image_picker: ^0.8.6+1
  location: ^4.4.0
  path_provider: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand.ttf
        
